title:            Alex Zvoleff
description:      Postdoctoral Associate at Conservation International
logo:             site-logo.png
disqus_shortname: azvoleff
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://azvoleff.github.io

# Owner/author information
owner:
  name:           Alex Zvoleff
  avatar:         headshot.jpg
  email:          azvoleff@conservation.org
  # Social networking links used in footer. Update and remove as you like.
  twitter:        azvoleff
  facebook:       
  github:         azvoleff
  stackexchange:  azvoleff
  linkedin:       azvoleff
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: CV
    url: /cv
  - title: Research
    url: /research
  - title: Blog
    url: /blog
  - title: Other
    url: /other

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Rmd"]

piwik:
  base_url: stats.azvoleff.com
  site_id: 5
